import { Restaurant } from './types';

export const DEPARTMENTS = [
  '모바일 앱 개발',
  'IT',
  '모바일 로보틱스',
  '메카트로닉스',
  '산업용 로봇',
] as const;

export type DepartmentName = (typeof DEPARTMENTS)[number];

export const DEPARTMENT_ALIASES: Record<DepartmentName, string[]> = {
  '모바일 앱 개발': ['모바일앱', '앱', '웹'],
  'IT': ['it', '네트워크', '시스템'],
  '모바일 로보틱스': ['모바일', '로보틱스', '모로'],
  '메카트로닉스': ['메카', '메카트로닉스'],
  '산업용 로봇': ['산업', '산업용', '로봇'],
};

export const MEMBER_DEPARTMENT_MAP: Record<string, DepartmentName> = {
  '김도현': '모바일 앱 개발',
  '박승제': '모바일 앱 개발',
  '조예성': 'IT',
  '천현승': 'IT',
  '강경완': '모바일 로보틱스',
  '김현수2': '모바일 로보틱스',
  '효정 선배': '모바일 로보틱스',
  '효정선배': '모바일 로보틱스',
  '조윤성': '모바일 로보틱스',
  '조준호': '메카트로닉스',
  '윤준영': '메카트로닉스',
  '김현수': '메카트로닉스',
  '하수민': '메카트로닉스',
  '최지성': '메카트로닉스',
  '최예서': '메카트로닉스',
  '승윤 선배': '산업용 로봇',
  '승윤선배': '산업용 로봇',
  '이시형': '산업용 로봇',
  '정지훈': '산업용 로봇',
};

export const DEFAULT_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-2',
    name: '강적 꼬막짬뽕',
    menuItems: [
      { id: 'menu-2-1', name: '짜장면', aliases: ['짜장'] },
      { id: 'menu-2-1-p', name: '짜장면(포장)', aliases: ['짜장면포장', '짜장포장', '짜장면 포장'] },
      { id: 'menu-2-2', name: '짜장밥', aliases: ['짜밥', '짜장 밥'] },
      { id: 'menu-2-2-p', name: '짜장밥(포장)', aliases: ['짜밥포장', '짜장밥 포장', '짜장 밥 포장'] },
      { id: 'menu-2-3', name: '꼬막짬뽕', aliases: ['꼬짬', '꼬막'] },
      { id: 'menu-2-3-p', name: '꼬막짬뽕(포장)', aliases: ['꼬짬포장', '꼬막포장', '꼬막짬뽕 포장'] },
      { id: 'menu-2-4', name: '꼬막짬뽕밥', aliases: ['꼬짬밥', '꼬짬 밥', '꼬막 밥'] },
      { id: 'menu-2-4-p', name: '꼬막짬뽕밥(포장)', aliases: ['꼬짬밥포장', '꼬짬 밥 포장', '꼬막짬뽕밥 포장'] },
      { id: 'menu-2-5', name: '해물짬뽕', aliases: ['해짬'] },
      { id: 'menu-2-5-p', name: '해물짬뽕(포장)', aliases: ['해짬포장', '해물짬뽕 포장'] },
      { id: 'menu-2-6', name: '해물짬뽕밥', aliases: ['해짬밥', '해짬 밥'] },
      { id: 'menu-2-6-p', name: '해물짬뽕밥(포장)', aliases: ['해짬밥포장', '해짬 밥 포장', '해물짬뽕밥 포장'] },
      { id: 'menu-2-7', name: '순두부짬뽕', aliases: ['순두부', '순짬'] },
      { id: 'menu-2-7-p', name: '순두부짬뽕(포장)', aliases: ['순두부포장', '순짬포장', '순두부짬뽕 포장'] },
      { id: 'menu-2-8', name: '순두부짬뽕밥', aliases: ['순두부밥', '순짬밥', '순두부 밥', '순짬 밥'] },
      { id: 'menu-2-8-p', name: '순두부짬뽕밥(포장)', aliases: ['순두부밥포장', '순짬밥포장', '순두부 밥 포장', '순두부짬뽕밥 포장'] },
      { id: 'menu-2-9', name: '찹쌀탕수육', aliases: ['탕수육', '찹탕'] },
      { id: 'menu-2-10', name: '공기밥', aliases: ['공밥'] },
      { id: 'menu-2-11', name: '만두', aliases: ['군만두'] },
      { id: 'menu-2-12', name: '음료수', aliases: ['콜라', '사이다', '음료'] },
    ],
  },
  {
    id: 'rest-3',
    name: '한솥도시락',
    menuItems: [
      { id: 'menu-3-1', name: '치킨마요', aliases: ['치마'] },
      { id: 'menu-3-2', name: '빅치킨마요', aliases: ['빅치마'] },
      { id: 'menu-3-3', name: '메가치킨마요', aliases: ['메가치마'] },
      { id: 'menu-3-4', name: '스팸마요', aliases: ['스마'] },
      { id: 'menu-3-5', name: '참치마요', aliases: ['참마'] },
      { id: 'menu-3-6', name: '숯불직화구이 덮밥', aliases: ['숯불덮밥', '직화덮밥', '숯불직화구이덮밥'] },
      { id: 'menu-3-7', name: '돼지불백 덮밥', aliases: ['돼지불백', '돼지불백덮밥'] },
      { id: 'menu-3-8', name: '제많덮(제육 많이 덮밥)', aliases: ['제많덮', '제육많이덮밥'] },
      { id: 'menu-3-9', name: '빅 제많덮(빅 제육 많이 덮밥)', aliases: ['빅제많덮'] },
      { id: 'menu-3-10', name: '김치 제육 덮밥', aliases: ['김치제육덮밥', '김제덮'] },
      { id: 'menu-3-11', name: '김치 참치 덮밥', aliases: ['김치참치덮밥'] },
      { id: 'menu-3-12', name: '돈까스 덮밥', aliases: ['돈까스덮밥', '돈덮'] },
      { id: 'menu-3-13', name: '돈까스 카레', aliases: ['돈까스카레'] },
      { id: 'menu-3-14', name: '왕카레돈까스 덮밥', aliases: ['왕카레돈까스덮밥'] },
      { id: 'menu-3-15', name: '왕카레치킨 덮밥', aliases: ['왕카레치킨덮밥'] },
      { id: 'menu-3-16', name: '왕김치돈까스 덮밥', aliases: ['왕김치돈까스덮밥'] },
      { id: 'menu-3-17', name: '오리지널 치즈 닭갈비덮밥', aliases: ['치즈닭갈비덮밥', '치닭덮'] },
      { id: 'menu-3-18', name: '핫 치즈 닭갈비덮밥', aliases: ['핫치즈닭갈비'] },
      { id: 'menu-3-19', name: '돈까스도련님 고기고기', aliases: ['돈도고기고기', '돈도고기'] },
      { id: 'menu-3-20', name: '카츠카츠 고기고기', aliases: ['카츠카츠고기고기'] },
      { id: 'menu-3-21', name: '돈치 고기고기', aliases: ['돈치고기고기'] },
      { id: 'menu-3-22', name: '새치 고기고기', aliases: ['새치고기고기'] },
      { id: 'menu-3-23', name: '돈까스도련님', aliases: ['돈도'] },
      { id: 'menu-3-24', name: '제육 돈까스도련님', aliases: ['제육돈까스도련님'] },
      { id: 'menu-3-25', name: '칠리 찹쌀탕수육도련님', aliases: ['칠리탕수육도련님', '탕수육도련님'] },
      { id: 'menu-3-26', name: '돈치스팸', aliases: ['돈치스팸'] },
      { id: 'menu-3-27', name: '동백', aliases: ['동백도시락'] },
      { id: 'menu-3-28', name: '송정식 떡갈비', aliases: ['송정식떡갈비', '떡갈비'] },
      { id: 'menu-3-29', name: '치킨제육', aliases: ['치제'] },
      { id: 'menu-3-30', name: '한우 함박스테이크&토네이도 소세지', aliases: ['한우함박'] },
      { id: 'menu-3-31', name: '한우 함박스테이크& 청양 토네이도 소세지', aliases: ['청양함박'] },
      { id: 'menu-3-32', name: '더블 돈까스도련님', aliases: ['더블돈도'] },
      { id: 'menu-3-33', name: '더블 칠리 찹쌀탕수육도련님', aliases: ['더블칠리탕수육도련님'] },
      { id: 'menu-3-34', name: '진달래', aliases: ['진달래도시락'] },
      { id: 'menu-3-35', name: '해바라기', aliases: ['해바라기도시락'] },
      { id: 'menu-3-36', name: '매화 고등어', aliases: ['매화고등어'] },
      { id: 'menu-3-37', name: '매화 연어', aliases: ['매화연어'] },
      { id: 'menu-3-38', name: '스페셜 한우함박스테이크 도시락', aliases: ['스페셜한우함박'] },
      { id: "menu-3-39", "name": "스페셜 해바라기 도시락", "aliases": ["스페셜해바라기"] },
      { id: "menu-3-40", "name": "스페셜 숯불직화 진달래 도시락", "aliases": ["스페셜진달래"] },
      { id: "menu-3-41", "name": "스페셜 송정식 떡갈비 도시락", "aliases": ["스페셜떡갈비"] },
      { id: "menu-3-42", "name": "김치볶음밥", "aliases": ["김볶"] },
      { id: "menu-3-43", "name": "스팸 김치볶음밥", "aliases": ["스팸김볶"] },
      { id: "menu-3-44", "name": "김치볶음밥&돼지불백", "aliases": ["김볶돼지불백"] },
      { id: "menu-3-45", "name": "소불고기 감초고추장 비빔밥", "aliases": ["소불고기비빔밥"] },
      { id: "menu-3-46", "name": "시골제육 두부강된장 비빔밥", "aliases": ["제육강된장비빔밥"] },
      { id: "menu-3-47", "name": "참치야채 감초고추장 비빔밥", "aliases": ["참치비빔밥"] },
      { id: "menu-3-48", "name": "열무 감초고추장 비빔밥", "aliases": ["열무비빔밥"] },
      { id: "menu-3-49", "name": "부대찌개", "aliases": ["부대찌개도시락"] },
      { id: "menu-3-50", "name": "묵은지 김치찌개", "aliases": ["김치찌개도시락"] },
      { id: "menu-3-51", "name": "치킨마요 부대찌개 정식", "aliases": ["치킨마요부대찌개정식"] },
      { id: "menu-3-52", "name": "빅치킨마요 부대찌개 정식", "aliases": ["빅치킨마요부대찌개정식"] },
      { id: "menu-3-53", "name": "단품 부대찌개", "aliases": [] },
      { id: "menu-3-54", "name": "단품 묵은지 김치찌개", "aliases": [] },
      { "id": "menu-3-55", "name": "단품 카레", "aliases": [] },
      { "id": "menu-3-56", "name": "반찬 돈까스도련님", "aliases": [] },
      { "id": "menu-3-57", "name": "반찬 치킨", "aliases": [] },
      { "id": "menu-3-58", "name": "반찬 제육볶음", "aliases": [] },
      { "id": "menu-3-59", "name": "반찬 돈까스", "aliases": [] },
      { "id": "menu-3-60", "name": "한솥 닭강정(소)", "aliases": ["닭강정소", "닭강정"] },
      { "id": "menu-3-61", "name": "한솥 닭강정(중)", "aliases": ["닭강정중"] },
      { "id": "menu-3-62", "name": "크림 닭강정(소)", "aliases": [] },
      { "id": "menu-3-63", "name": "크림 닭강정(중)", "aliases": [] },
      { "id": "menu-3-64", "name": "김피탕", "aliases": [] },
      { "id": "menu-3-65", "name": "해시 포테이토 스틱", "aliases": ["해시포테이토"] },
      { "id": "menu-3-66", "name": "케이준후라이", "aliases": ["감자튀김", "케이준"] }
    ],
  },
  {
    id: 'rest-1',
    name: '송정돼지국밥',
    menuItems: [
      { id: 'menu-1-1', name: '돼지국밥', aliases: ['국밥', '돼지 국밥'] },
      { id: 'menu-1-2', name: '돼지국밥(특)', aliases: ['특', '국밥특', '돼지국밥 특'] },
      { id: 'menu-1-3', name: '얼큰국밥', aliases: ['얼큰', '얼큰 국밥'] },
      { id: 'menu-1-4', name: '고기국수', aliases: ['고국', '고기 국수'] },
      { id: 'menu-1-5', name: '돔베고기', aliases: [] },
    ],
  },
  {
    id: 'rest-4',
    name: '마미쿡',
    menuItems: [
      { id: 'menu-4-1', name: '마마통살버거(단품)', aliases: [] },
      { id: 'menu-4-2', name: '마마통살버거(세트)', aliases: ['마마세트'] },
      { id: 'menu-4-3', name: '불새우버거(단품)', aliases: [] },
      { id: 'menu-4-4', name: '불새우버거(세트)', aliases: [] },
    ],
  },
];
